#!/usr/bin/env bash

if [ ! -e .files_to_be_formatted ]; then
  exit 0
fi

FILES=$(cat .files_to_be_formatted)
rm .files_to_be_formatted

if [ -z "$FILES" ]; then
  exit 0
fi

deno fmt -L info $FILES
git add $FILES
git commit --amend -C HEAD --no-verify
